//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokEkstresi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STI { get; set; }
        public virtual DbSet<STK> STK { get; set; }
    
        public virtual ObjectResult<sp_stokListesi_Result> sp_stokListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stokListesi_Result>("sp_stokListesi");
        }
    
        public virtual ObjectResult<UrunGetir_Result> UrunGetir(string malKodu, Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var malKoduParameter = malKodu != null ?
                new ObjectParameter("malKodu", malKodu) :
                new ObjectParameter("malKodu", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("baslangicTarihi", baslangicTarihi) :
                new ObjectParameter("baslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("bitisTarihi", bitisTarihi) :
                new ObjectParameter("bitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunGetir_Result>("UrunGetir", malKoduParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    }
}
